### ISSUE TITLE
dead links

### ISSUE THREAD

**Issue by mikebarr58** [eoinkelly/ember-runloop-handbook#14]
Hey, thanks for the write-up, very helpful. Just fyi, I noticed a few dead links in case you wanted to update them

1) "runloop Guide", which is used here

 "You can see a summary of the purpose of each queue in the runloop Guide but here we are going to focus on the queues themselves."

and here

 "The runloop Guide has an excellent visualisation of how jobs are run but in brief"

2) "Ember container", which is used here

" ... but it is important to note that there is not a single instance of the runloop in memory (unlike the Ember container which is a singleton). "

3) "noisy runloop kit", which is used here

"This repo also contains the noisy runloop kit which is trivial demo app and a copy of Ember that I have patched to be very noisy about what its runloop does."

Again, appreciate you doing such a detailed writeup, I found it very helpful.

**Comment by eoinkelly** [comment]
Thank you for letting me know about these :sparkles: - they should be fixed now.
